#kubectl apply -f nameofthemanifestfile
apiVersion: apps/v1 #we know the communication to your k8s strictly happen through api gateway
kind: Deployment #this is the type of API Service Pod Secret PresistentVOlume
metadata:
  name: myapp3-deployment #this is the name of the deployment which will be created

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myaap3-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp3-container
          image: stacksimplify/kubenginx:3.0.0
          ports:
            - containerPort: 80
