apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxapp-ingress-service
  
spec:
  rules:
  - http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-nginx-service
            port:
              number: 80